version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: s3,sqs,dynamodb
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: password
      PERSISTENCE: true
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data: