version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
    env_file:
      - ./.env
    restart: always