version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    environment:
      - REDIS_PASSWORD=password
    restart: always 

volumes:
  redis_data: