version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=password
    restart: always 

volumes:
  redis_data: