version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:./docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
  
volumes:
  mysql_data:
