version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    restart: always

  mysql-workbench:
    image: linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    ports:
      - '3000:3000'
    depends_on: 
      - mysql
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - IPC_LOCK
    restart: always
  
volumes:
  mysql_data:
